// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGS9WN4eOWiJR9RMgIpKx2pc9FUcq14c',
    appId: '1:295275829272:web:9a486c13a70b61dbe00b6d',
    messagingSenderId: '295275829272',
    projectId: 'quizapp-cf4a2',
    authDomain: 'quizapp-cf4a2.firebaseapp.com',
    databaseURL: 'https://quizapp-cf4a2.firebaseio.com',
    storageBucket: 'quizapp-cf4a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBctDzqJCRheSGCIFr_U-PWW5NnmlecmpE',
    appId: '1:295275829272:android:4a22ce8f8830d59fe00b6d',
    messagingSenderId: '295275829272',
    projectId: 'quizapp-cf4a2',
    databaseURL: 'https://quizapp-cf4a2.firebaseio.com',
    storageBucket: 'quizapp-cf4a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv4ByQRZneSUQiPmzpFITqsehbp010SgI',
    appId: '1:295275829272:ios:b1fe8dd2863c58e8e00b6d',
    messagingSenderId: '295275829272',
    projectId: 'quizapp-cf4a2',
    databaseURL: 'https://quizapp-cf4a2.firebaseio.com',
    storageBucket: 'quizapp-cf4a2.appspot.com',
    androidClientId: '295275829272-sc054prsnl94vfi46tns7j2nk7lmhve7.apps.googleusercontent.com',
    iosClientId: '295275829272-ebv9kj4b8es19c6a6fp4a66bf6a7393i.apps.googleusercontent.com',
    iosBundleId: 'com.divinetechs.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv4ByQRZneSUQiPmzpFITqsehbp010SgI',
    appId: '1:295275829272:ios:b1fe8dd2863c58e8e00b6d',
    messagingSenderId: '295275829272',
    projectId: 'quizapp-cf4a2',
    databaseURL: 'https://quizapp-cf4a2.firebaseio.com',
    storageBucket: 'quizapp-cf4a2.appspot.com',
    androidClientId: '295275829272-sc054prsnl94vfi46tns7j2nk7lmhve7.apps.googleusercontent.com',
    iosClientId: '295275829272-ebv9kj4b8es19c6a6fp4a66bf6a7393i.apps.googleusercontent.com',
    iosBundleId: 'com.divinetechs.quiz',
  );
}
